# project configuration determines what part of the pipeline and which model to run

project:
  paths: # defines data directories
    data: data/input # raw data path
    output: data/output
  pipeline:
    steps: # comment steps om amd pit as needed
      - churn_model.src.preprocess
      - churn_model.src.model
      - churn_model.src.forecast
    model_name: # model to run (specified in model configuration)

